#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18051
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSW.admin
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class AdminLayout : Nancy.ViewEngines.Razor.NancyRazorViewBase<dynamic>
{

#line hidden

public override void Execute()
{
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n  <head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <title>");


#line 6 "W:\DevnectFX\DSW\Views\admin\AdminLayout.cshtml"
      Write(ViewBag.Title);


#line default
#line hidden
WriteLiteral("</title>\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(" content=\"\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"author\"");

WriteLiteral(" content=\"\"");

WriteLiteral(" />\r\n\r\n    <!-- Le styles -->\r\n    <link");

WriteLiteral(" href=\"/common/bootstrap/css/bootstrap.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n      body {\r\n        padding-top: 60px;\r\n        padding-bottom: 40px;\r\n     " +
" }\r\n      .sidebar-nav {\r\n        padding: 9px 0;\r\n      }\r\n\r\n      ");

WriteLiteral("@media (max-width: 980px) {\r\n        /* Enable use of floated navbar text */\r\n   " +
"     .navbar-text.pull-right {\r\n          float: none;\r\n          padding-left: " +
"5px;\r\n          padding-right: 5px;\r\n        }\r\n      }\r\n    </style>\r\n    <link" +
"");

WriteLiteral(" href=\"/common/bootstrap/css/bootstrap-responsive.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->\r\n    <!--[if " +
"lt IE 9]>\r\n      <script");

WriteLiteral(" src=\"/common/bootstrap/js/html5shiv.js\"");

WriteLiteral("></script>\r\n    <![endif]-->\r\n\r\n    <!-- Fav and touch icons -->\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon-precomposed\"");

WriteLiteral(" sizes=\"144x144\"");

WriteLiteral(" href=\"/common/bootstrap/ico/apple-touch-icon-144-precomposed.png\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"apple-touch-icon-precomposed\"");

WriteLiteral(" sizes=\"114x114\"");

WriteLiteral(" href=\"/common/bootstrap/ico/apple-touch-icon-114-precomposed.png\"");

WriteLiteral(">\r\n      <link");

WriteLiteral(" rel=\"apple-touch-icon-precomposed\"");

WriteLiteral(" sizes=\"72x72\"");

WriteLiteral(" href=\"/common/bootstrap/ico/apple-touch-icon-72-precomposed.png\"");

WriteLiteral(">\r\n                    <link");

WriteLiteral(" rel=\"apple-touch-icon-precomposed\"");

WriteLiteral(" href=\"/common/bootstrap/ico/apple-touch-icon-57-precomposed.png\"");

WriteLiteral(">\r\n                                   <link");

WriteLiteral(" rel=\"shortcut icon\"");

WriteLiteral(" href=\"/common/bootstrap/ico/favicon.png\"");

WriteLiteral(">\r\n  </head>\r\n\r\n  <body>\r\n\r\n    <div");

WriteLiteral(" class=\"navbar navbar-inverse navbar-fixed-top\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"navbar-inner\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n          <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-navbar\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\".nav-collapse\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n            <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n            <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n          </button>\r\n          <a");

WriteLiteral(" class=\"brand\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Project name</a>\r\n          <div");

WriteLiteral(" class=\"nav-collapse collapse\"");

WriteLiteral(">\r\n            <p");

WriteLiteral(" class=\"navbar-text pull-right\"");

WriteLiteral(">\r\n              Logged in as <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"navbar-link\"");

WriteLiteral(">Username</a>\r\n            </p>\r\n            <ul");

WriteLiteral(" class=\"nav\"");

WriteLiteral(">\r\n              <li");

WriteLiteral(" class=\"active\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Home</a></li>\r\n              <li><a");

WriteLiteral(" href=\"#about\"");

WriteLiteral(">About</a></li>\r\n              <li><a");

WriteLiteral(" href=\"#contact\"");

WriteLiteral(">Contact</a></li>\r\n            </ul>\r\n          </div><!--/.nav-collapse -->\r\n   " +
"     </div>\r\n      </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"row-fluid\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"span2\"");

WriteLiteral(">\r\n          <div");

WriteLiteral(" class=\"well sidebar-nav\"");

WriteLiteral(">\r\n            <ul");

WriteLiteral(" class=\"nav nav-list\"");

WriteLiteral(">\r\n              <li");

WriteLiteral(" class=\"nav-header\"");

WriteLiteral(">Sidebar</li>\r\n              <li");

WriteLiteral(" class=\"active\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Link</a></li>\r\n              <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Link</a></li>\r\n              <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Link</a></li>\r\n              <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Link</a></li>\r\n              <li");

WriteLiteral(" class=\"nav-header\"");

WriteLiteral(">Sidebar</li>\r\n              <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Link</a></li>\r\n              <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Link</a></li>\r\n              <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Link</a></li>\r\n              <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Link</a></li>\r\n              <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Link</a></li>\r\n              <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Link</a></li>\r\n              <li");

WriteLiteral(" class=\"nav-header\"");

WriteLiteral(">Sidebar</li>\r\n              <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Link</a></li>\r\n              <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Link</a></li>\r\n              <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Link</a></li>\r\n            </ul>\r\n          </div><!--/.well -->\r\n        </div>" +
"<!--/span-->\r\n        <div");

WriteLiteral(" class=\"span9\"");

WriteLiteral(">\r\n");

WriteLiteral("          ");


#line 96 "W:\DevnectFX\DSW\Views\admin\AdminLayout.cshtml"
     Write(RenderBody());


#line default
#line hidden
WriteLiteral(@"
        </div><!--/span-->
      </div><!--/row-->

      <hr />

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->


  </body>
</html>
");

}
}
}
#pragma warning restore 1591
