#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18051
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSW.admin
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class AdminLayout : Nancy.ViewEngines.Razor.NancyRazorViewBase<dynamic>
{

#line hidden

public override void Execute()
{
WriteLiteral("<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"ko\"");

WriteLiteral(">\r\n  <head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <title>");


#line 6 "W:\DevnectFX\DSW\Views\admin\AdminLayout.cshtml"
      Write(ViewBag.Title);


#line default
#line hidden
WriteLiteral("</title>\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"description\"");

WriteLiteral(" content=\"\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"author\"");

WriteLiteral(" content=\"\"");

WriteLiteral(" />\r\n\r\n    <!-- Le styles -->\r\n    <link");

WriteLiteral(" href=\"/common/bootstrap/css/bootstrap.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n      body {\r\n        padding-top: 60px;\r\n        padding-bottom: 40px;\r\n     " +
" }\r\n      .sidebar-nav {\r\n        padding: 9px 0;\r\n      }\r\n\r\n      ");

WriteLiteral("@media (max-width: 980px) {\r\n        /* Enable use of floated navbar text */\r\n   " +
"     .navbar-text.pull-right {\r\n          float: none;\r\n          padding-left: " +
"5px;\r\n          padding-right: 5px;\r\n        }\r\n      }\r\n    </style>\r\n    <link" +
"");

WriteLiteral(" href=\"/common/bootstrap/css/bootstrap-responsive.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/common/kendoui.web/styles/kendo.common.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"/common/kendoui.web/styles/kendo.default.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <script");

WriteLiteral(" src=\"/common/kendoui.web/js/jquery.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/common/kendoui.web/js/kendo.all.min.js\"");

WriteLiteral("></script>\r\n\r\n\r\n    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->\r\n   " +
" <!--[if lt IE 9]>\r\n      <script");

WriteLiteral(" src=\"/common/bootstrap/js/html5shiv.js\"");

WriteLiteral("></script>\r\n    <![endif]-->\r\n    \r\n    <script>\r\n        $(document).ready(funct" +
"ion() {\r\n            $(\"#panelbar\").kendoPanelBar();\r\n        });\r\n    </script>" +
"\r\n  </head>\r\n\r\n  <body>\r\n    <div");

WriteLiteral(" class=\"navbar navbar-inverse navbar-fixed-top\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"navbar-inner\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n          <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-navbar\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\".nav-collapse\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n            <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n            <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n          </button>\r\n          <a");

WriteLiteral(" class=\"brand\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">愿由ъ옄 ?섏씠吏</a>\r\n          <div");

WriteLiteral(" class=\"nav-collapse collapse\"");

WriteLiteral(">\r\n            <p");

WriteLiteral(" class=\"navbar-text pull-right\"");

WriteLiteral(">\r\n              <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"navbar-link\"");

WriteLiteral(">愿由ъ옄(admin)</a> <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"navbar-link\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-remove-sign\"");

WriteLiteral("></i> Logout</a>\r\n            </p>\r\n            <ul");

WriteLiteral(" class=\"nav\"");

WriteLiteral(">\r\n              <li");

WriteLiteral(" class=\"active\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">?쒖뒪?쒓?由?/a></li>\r\n              <li><a");

WriteLiteral(" href=\"#about\"");

WriteLiteral(">硫붾돱2</a></li>\r\n              <li><a");

WriteLiteral(" href=\"#contact\"");

WriteLiteral(">硫붾돱3</a></li>\r\n            </ul>\r\n          </div><!--/.nav-collapse -->\r\n      " +
"  </div>\r\n      </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"span3\"");

WriteLiteral(">\r\n          <div");

WriteLiteral(" class=\"k-content\"");

WriteLiteral(">\r\n          \t<ul");

WriteLiteral(" id=\"panelbar\"");

WriteLiteral(">\r\n          \t\t<li");

WriteLiteral(" class=\"k-state-active\"");

WriteLiteral("><span");

WriteLiteral(" class=\"k-link k-state-selected\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-th-list\"");

WriteLiteral("></i> 硫붾돱愿由?/span>\r\n          \t\t\t<ul>\r\n          \t\t\t\t<li><i");

WriteLiteral(" class=\"icon-chevron-right\"");

WriteLiteral("></i> 硫붾돱?깅줉愿由?/li>\r\n          \t\t\t\t<li><i");

WriteLiteral(" class=\"icon-chevron-right\"");

WriteLiteral("></i> ?ъ슜?먮찓?닿?由?/li>\r\n          \t\t\t\t<li><i");

WriteLiteral(" class=\"icon-chevron-right\"");

WriteLiteral("></i> 洹몃９硫붾돱愿由?/li>\r\n      \t\t\t\t</ul>\r\n          \t\t</li>\r\n          \t\t<li><span");

WriteLiteral(" class=\"k-link\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-th-list\"");

WriteLiteral("></i> ?ъ슜??洹몃９愿由?/span>\r\n          \t\t\t<ul>\r\n          \t\t\t\t<li><i");

WriteLiteral(" class=\"icon-chevron-right\"");

WriteLiteral("></i> ?ъ슜?먭?由?/li>\r\n          \t\t\t\t<li><i");

WriteLiteral(" class=\"icon-chevron-right\"");

WriteLiteral("></i> 洹몃９愿由?/li>\r\n      \t\t\t\t</ul>\r\n      \t\t\t</li>\r\n          \t</ul>\r\n          <" +
"/div>\r\n        </div><!--/span-->\r\n        <div");

WriteLiteral(" class=\"span9\"");

WriteLiteral(">\r\n");

WriteLiteral("        \t");


#line 96 "W:\DevnectFX\DSW\Views\admin\AdminLayout.cshtml"
    Write(RenderBody());


#line default
#line hidden
WriteLiteral("\r\n        </div><!--/span-->\r\n      </div><!--/row-->\r\n\r\n      <hr />\r\n\r\n      <f" +
"ooter>\r\n        <p>&copy; Company 2013</p>\r\n      </footer>\r\n\r\n    </div><!--/.f" +
"luid-container-->\r\n  </body>\r\n</html>\r\n");

}
}
}
#pragma warning restore 1591
