#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18051
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSW.admin
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class Default : DSW.ViewEngines.Razor.DSWRazorViewBase<dynamic>
{

#line hidden

public override void Execute()
{

#line 2 "W:\DevnectFX\DSW\Views\admin\Default.cshtml"
   ViewBag.Title = "愿由ъ옄 ?섏씠吏"; 

#line default
#line hidden
WriteLiteral("\r\n!");


#line 3 "W:\DevnectFX\DSW\Views\admin\Default.cshtml"
Write(this);


#line default
#line hidden
WriteLiteral("!\r\n");

}
}
}
#pragma warning restore 1591
