#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18051
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSW.Test
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class Test : DSW.ViewEngines.Razor.DSWRazorViewBase<dynamic>
{

#line hidden

public override void Execute()
{
WriteLiteral("<html>\r\n\t<head>\r\n\t\t<title>");


#line 4 "W:\DevnectFX\DSW\Views\Test\Test.cshtml"
    Write(DateTime.Now);


#line default
#line hidden
WriteLiteral("</title>\r\n\t</head>\r\n\t<body>\r\n\t!");


#line 7 "W:\DevnectFX\DSW\Views\Test\Test.cshtml"
Write(this);


#line default
#line hidden
WriteLiteral("!\r\n\t</body>\r\n</html>\r\n");

}
}
}
#pragma warning restore 1591
